# Generated by Django 4.2 on 2023-07-04 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("legal", "Legal"), ("individual", "Individual")],
                        default="individual",
                        max_length=256,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_moderation", "In Moderation"),
                            ("declined", "Declined"),
                            ("accepted", "Accepted"),
                        ],
                        default="in_moderation",
                        max_length=256,
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(default=1000, verbose_name="Amount of Money"),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("transfer", "Transfer"),
                        ],
                        default="cash",
                        max_length=256,
                    ),
                ),
                ("comment", models.TextField(verbose_name="Comment")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sponsor",
                "verbose_name_plural": "Sponsors",
            },
        ),
    ]
