# Generated by Django 4.2 on 2023-07-06 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_alter_university_name"),
        ("sponsor", "0002_sponsorship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsorship",
            name="sponsor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sponsorships",
                to="sponsor.sponsor",
                verbose_name="Sponsor",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorship",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sponsors",
                to="student.student",
                verbose_name="Student",
            ),
        ),
    ]
