# Generated by Django 4.2 on 2023-07-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="course",
        ),
        migrations.RemoveField(
            model_name="user",
            name="faculty",
        ),
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("google", "Google"),
                    ("twitter", "Twitter"),
                    ("email", "Email"),
                ],
                default="email",
                max_length=255,
            ),
        ),
    ]
